import type { GooglePlaceId } from './contracts';
import { asGooglePlaceId, ContractValidationError, isRecord } from './validation';

export const PLACE_BUSINESS_STATUSES = [
  'OPERATIONAL',
  'CLOSED_TEMPORARILY',
  'CLOSED_PERMANENTLY',
  'UNKNOWN',
] as const;

export type PlaceBusinessStatus = typeof PLACE_BUSINESS_STATUSES[number];

export type PlaceTimePoint = {
  day: number;
  hour: number;
  minute: number;
};

export type PlaceOpeningPeriod = {
  open: PlaceTimePoint;
  close?: PlaceTimePoint;
};

export type PlaceOpeningHours = {
  periods: PlaceOpeningPeriod[];
  weekdayDescriptions: string[];
  openNow?: boolean;
};

/**
 * Provenance metadata for live place intelligence.
 * - `fetchedAt`: Server/provider observation-side timestamp generated by Edge Function when upstream fact was fetched.
 * - `receivedAt`: Client receipt-side timestamp recorded when client received and validated the payload.
 * Neither timestamp represents Google's factual last-update time.
 * No absolute ordering is enforced between fetchedAt and receivedAt due to potential server/client clock skew.
 */
export type PlaceIntelligenceProvenance = {
  provider: 'google-places';
  boundary: 'get-place-metadata';
  observation: 'CLIENT_RECEIVED';
  fetchedAt: string;
  receivedAt: string;
};

export type PlaceIntelligence = {
  kind: 'live-place-intelligence';
  googlePlaceId: GooglePlaceId;
  businessStatus: PlaceBusinessStatus;
  openingHours: PlaceOpeningHours | null;
  utcOffsetMinutes?: number;
  rating?: number;
  userRatingCount?: number;
  provenance: PlaceIntelligenceProvenance;
};

export type PlaceIntelligenceRequest = {
  googlePlaceId: GooglePlaceId;
};

export interface PlaceIntelligenceRepository {
  getIntelligence(googlePlaceId: GooglePlaceId, signal?: AbortSignal): Promise<PlaceIntelligence>;
}

function only(value: unknown, keys: readonly string[]): value is Record<string, unknown> {
  return isRecord(value) && Object.keys(value).every((key) => keys.includes(key));
}

function timestamp(value: unknown, name: string): string {
  if (
    typeof value !== 'string' ||
    !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/.test(value) ||
    !Number.isFinite(Date.parse(value))
  ) {
    throw new ContractValidationError(name);
  }
  return value;
}

export function validatePlaceIntelligenceRequest(value: unknown): PlaceIntelligenceRequest {
  if (!isRecord(value) || !only(value, ['googlePlaceId']) || typeof value.googlePlaceId !== 'string') {
    throw new ContractValidationError('place intelligence request');
  }
  return {
    googlePlaceId: asGooglePlaceId(value.googlePlaceId),
  };
}

export function validatePlaceBusinessStatus(value: unknown): PlaceBusinessStatus {
  if (value === null || value === undefined) {
    return 'UNKNOWN';
  }
  if (typeof value === 'string' && PLACE_BUSINESS_STATUSES.includes(value as PlaceBusinessStatus)) {
    return value as PlaceBusinessStatus;
  }
  throw new ContractValidationError('place business status');
}

function validateTimePoint(value: unknown): PlaceTimePoint {
  if (
    !isRecord(value) ||
    !only(value, ['day', 'hour', 'minute']) ||
    typeof value.day !== 'number' || !Number.isInteger(value.day) || value.day < 0 || value.day > 6 ||
    typeof value.hour !== 'number' || !Number.isInteger(value.hour) || value.hour < 0 || value.hour > 23 ||
    typeof value.minute !== 'number' || !Number.isInteger(value.minute) || value.minute < 0 || value.minute > 59
  ) {
    throw new ContractValidationError('opening hours time point');
  }
  return { day: value.day, hour: value.hour, minute: value.minute };
}

function validateOpeningPeriod(value: unknown): PlaceOpeningPeriod {
  if (!isRecord(value) || !only(value, ['open', 'close'])) {
    throw new ContractValidationError('opening hours period');
  }
  const open = validateTimePoint(value.open);
  const close = value.close !== undefined ? validateTimePoint(value.close) : undefined;
  return { open, ...(close ? { close } : {}) };
}

export function validatePlaceOpeningHours(value: unknown): PlaceOpeningHours | null {
  if (value === null || value === undefined) return null;
  if (!isRecord(value) || !only(value, ['periods', 'weekdayDescriptions', 'openNow'])) {
    throw new ContractValidationError('opening hours');
  }

  if (!Array.isArray(value.periods) || value.periods.length > 28) {
    throw new ContractValidationError('opening hours periods');
  }
  const periods = value.periods.map(validateOpeningPeriod);

  if (!Array.isArray(value.weekdayDescriptions) || value.weekdayDescriptions.length > 7) {
    throw new ContractValidationError('opening hours weekday descriptions');
  }
  const weekdayDescriptions: string[] = [];
  for (const desc of value.weekdayDescriptions) {
    if (typeof desc !== 'string' || desc.length > 200) {
      throw new ContractValidationError('opening hours weekday description item');
    }
    weekdayDescriptions.push(desc.trim());
  }

  if (value.openNow !== undefined && typeof value.openNow !== 'boolean') {
    throw new ContractValidationError('opening hours openNow');
  }

  return {
    periods,
    weekdayDescriptions,
    ...(value.openNow !== undefined ? { openNow: value.openNow } : {}),
  };
}

export function validatePlaceIntelligence(value: unknown, fallbackReceivedAt?: string): PlaceIntelligence {
  if (!isRecord(value)) {
    throw new ContractValidationError('place intelligence');
  }

  const allowedKeys = [
    'kind',
    'googlePlaceId',
    'businessStatus',
    'openingHours',
    'utcOffsetMinutes',
    'rating',
    'userRatingCount',
    'provenance',
  ];
  if (!only(value, allowedKeys)) {
    throw new ContractValidationError('place intelligence payload keys');
  }

  if (value.kind !== undefined && value.kind !== 'live-place-intelligence') {
    throw new ContractValidationError('place intelligence kind');
  }

  const googlePlaceId = asGooglePlaceId(value.googlePlaceId);
  const businessStatus = validatePlaceBusinessStatus(value.businessStatus);
  const openingHours = validatePlaceOpeningHours(value.openingHours);

  let utcOffsetMinutes: number | undefined;
  if (value.utcOffsetMinutes !== undefined) {
    if (
      typeof value.utcOffsetMinutes !== 'number' ||
      !Number.isInteger(value.utcOffsetMinutes) ||
      value.utcOffsetMinutes < -840 ||
      value.utcOffsetMinutes > 840
    ) {
      throw new ContractValidationError('place intelligence utcOffsetMinutes');
    }
    utcOffsetMinutes = value.utcOffsetMinutes;
  }

  let rating: number | undefined;
  if (value.rating !== undefined) {
    if (typeof value.rating !== 'number' || !Number.isFinite(value.rating) || value.rating < 0 || value.rating > 5) {
      throw new ContractValidationError('place intelligence rating');
    }
    rating = value.rating;
  }

  let userRatingCount: number | undefined;
  if (value.userRatingCount !== undefined) {
    if (
      typeof value.userRatingCount !== 'number' ||
      !Number.isSafeInteger(value.userRatingCount) ||
      value.userRatingCount < 0
    ) {
      throw new ContractValidationError('place intelligence userRatingCount');
    }
    userRatingCount = value.userRatingCount;
  }

  if (
    !isRecord(value.provenance) ||
    !only(value.provenance, ['provider', 'boundary', 'observation', 'fetchedAt', 'receivedAt']) ||
    value.provenance.provider !== 'google-places' ||
    value.provenance.boundary !== 'get-place-metadata'
  ) {
    throw new ContractValidationError('place intelligence provenance');
  }

  const fetchedAt = timestamp(value.provenance.fetchedAt, 'place intelligence fetchedAt');
  const receivedAt = timestamp(
    value.provenance.receivedAt ?? fallbackReceivedAt ?? new Date().toISOString(),
    'place intelligence receivedAt',
  );

  return {
    kind: 'live-place-intelligence',
    googlePlaceId,
    businessStatus,
    openingHours,
    ...(utcOffsetMinutes !== undefined ? { utcOffsetMinutes } : {}),
    ...(rating !== undefined ? { rating } : {}),
    ...(userRatingCount !== undefined ? { userRatingCount } : {}),
    provenance: {
      provider: 'google-places',
      boundary: 'get-place-metadata',
      observation: 'CLIENT_RECEIVED',
      fetchedAt,
      receivedAt,
    },
  };
}
