import { MaterialIcons } from '@expo/vector-icons';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useMemo } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';

import { AppText } from '../../../components/AppText';
import type { SavedTripsRepository, TravelWorkspaceRepository } from '../../../integration/repositories';
import { SupabaseSavedTripsRepository, SupabaseTravelWorkspaceRepository } from '../../../integration/remote/supabaseTripRepositories';
import { supabase } from '../../../lib/supabase/client';
import type { RootStackParamList } from '../../../navigation/types';
import { useAuth } from '../../auth/AuthProvider';
import { useTranslation } from '../../../i18n';
import { useTheme } from '../../../theme';
import { radius, spacing, typography } from '../../../theme/tokens';
import type { ItineraryItem } from '../types';
import { useActivityEditorController } from '../useActivityEditorController';

type Props = NativeStackScreenProps<RootStackParamList, 'ActivityEditor'> & { savedTripsRepository?: SavedTripsRepository; workspaceRepository?: TravelWorkspaceRepository };
function isScheduleEligible(item: ItineraryItem | undefined): boolean {
  return !item || (item.workspaceItemKind !== 'note' && item.workspaceItemKind !== 'transport');
}

export function ActivityEditorScreen({ route, navigation, savedTripsRepository, workspaceRepository }: Props) {
  const { colors } = useTheme(); const { t } = useTranslation(); const { user } = useAuth();
  const savedRepo = useMemo(() => savedTripsRepository ?? new SupabaseSavedTripsRepository(supabase), [savedTripsRepository]);
  const workspaceRepo = useMemo(() => workspaceRepository ?? new SupabaseTravelWorkspaceRepository(supabase), [workspaceRepository]);
  const isAdd = route.params.mode === 'add';
  const controller = useActivityEditorController({ route: route.params, user, savedTripsRepository: savedRepo, workspaceRepository: workspaceRepo, onSuccess: () => navigation.goBack() });
  const { detail, loading, saving, mutationReady, title, dayId, startTime, endTime, flexibility, priority, note, errorKey, conflict, setTitle, setDayId, setStartTime, setEndTime, setFlexibility, setPriority, setNote, clearTime, submit, transitionStatus } = controller;
  const editItemId = route.params.mode === 'edit' ? route.params.itemId : '';
  const uiItem = useMemo(() => detail?.days.flatMap((day) => day.items).find((item) => item.id === editItemId), [detail, editItemId]);
  const scheduleEligible = isScheduleEligible(uiItem ? { workspaceItemKind: uiItem.itemKind } as ItineraryItem : undefined);
  const providerLocked = uiItem?.resolution === 'VERIFIED';
  if (loading) return <View style={[styles.center, { backgroundColor: colors.background.canvas }]}><ActivityIndicator color={colors.brand.primary} /></View>;
  return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={[styles.root, { backgroundColor: colors.background.canvas }]}>
    <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
      <View style={styles.header}><Pressable accessibilityLabel={t('common.back')} accessibilityRole="button" onPress={() => navigation.goBack()} style={styles.iconButton}><MaterialIcons color={colors.text.primary} name="arrow-back" size={24} /></Pressable><AppText variant="title" style={styles.title}>{t(isAdd ? 'workspaceEditor.addTitle' : 'workspaceEditor.editTitle')}</AppText></View>
      {providerLocked ? <View accessibilityRole="text" style={[styles.locked, { backgroundColor: colors.background.surface, borderColor: colors.border.default }]}><MaterialIcons color={colors.text.muted} name="lock" size={18}/><AppText>{t('workspaceEditor.lockedProvider')}</AppText><AppText style={styles.lockedName}>{uiItem?.placeName}</AppText></View> : <Field label={t('workspaceEditor.activityTitle')} value={title} onChangeText={setTitle} placeholder={t('workspaceEditor.activityTitlePlaceholder')} error={errorKey === 'workspaceEditor.titleRequired' ? t(errorKey) : undefined} colors={colors} />}
      {isAdd && <View><AppText style={styles.label}>{t('workspaceEditor.day')}</AppText><View style={styles.chips}>{detail?.days.map((day) => <Choice key={day.id} label={`${t('workspaceEditor.day')} ${day.dayNumber}`} selected={dayId === day.id} onPress={() => setDayId(day.id)} colors={colors}/>)}</View></View>}
      {scheduleEligible ? <><AppText style={styles.label}>{t('workspaceEditor.timeHint')}</AppText><View style={styles.timeRow}><Field label={t('workspaceEditor.startTime')} value={startTime} onChangeText={setStartTime} placeholder="HH:MM" colors={colors}/><Field label={t('workspaceEditor.endTime')} value={endTime} onChangeText={setEndTime} placeholder="HH:MM" colors={colors}/></View><Pressable accessibilityRole="button" accessibilityLabel={t('workspaceEditor.clearTime')} onPress={clearTime} style={styles.clear}><AppText>{t('workspaceEditor.clearTime')}</AppText></Pressable>{errorKey && ['workspaceEditor.timeInvalid','workspaceEditor.timeRange'].includes(errorKey) ? <AppText style={{color: colors.state.error}}>{t(errorKey)}</AppText> : null}</> : <AppText style={{color: colors.text.muted}}>{t('workspaceEditor.noSchedule')}</AppText>}
      <SelectGroup title={t('workspaceEditor.flexibility')} value={flexibility} values={['fixed','flexible'] as const} onChange={setFlexibility} t={t} colors={colors}/><SelectGroup title={t('workspaceEditor.priority')} value={priority} values={['must_do','want_to_do','optional'] as const} onChange={setPriority} t={t} colors={colors}/>
      {!isAdd ? <View style={styles.field}><AppText style={styles.label}>{t('workspaceEditor.note')}</AppText><TextInput accessibilityLabel={t('workspaceEditor.note')} maxLength={500} multiline numberOfLines={4} onChangeText={setNote} placeholder={t('workspaceEditor.notePlaceholder')} placeholderTextColor={colors.text.muted} style={[styles.input, styles.noteInput, {backgroundColor:colors.background.surface,color:colors.text.primary,borderColor:errorKey === 'workspaceEditor.noteTooLong' ? colors.state.error : colors.border.default}]} textAlignVertical="top" value={note}/>{errorKey === 'workspaceEditor.noteTooLong' ? <View accessibilityRole="alert"><AppText style={{color:colors.state.error}}>{t(errorKey)}</AppText></View> : <AppText style={{color:colors.text.muted}}>{t('workspaceEditor.noteHint')}</AppText>}</View> : null}
      {!isAdd && uiItem ? <View style={[styles.statusPanel, {backgroundColor:colors.background.surface,borderColor:colors.border.default}]}><View style={styles.statusHeading}><MaterialIcons color={uiItem.activityStatus === 'completed' ? colors.state.success : colors.brand.primary} name={uiItem.activityStatus === 'completed' ? 'check-circle' : uiItem.activityStatus === 'skipped' ? 'skip-next' : 'schedule'} size={20}/><AppText style={styles.label}>{t('workspaceEditor.status')}</AppText><AppText style={{color:colors.text.muted}}>{t(`workspaceEditor.status.${uiItem.activityStatus}`)}</AppText></View><View style={styles.statusActions}>{uiItem.activityStatus === 'scheduled' ? <><StatusAction colors={colors} disabled={saving || !mutationReady} icon="check-circle" label={t('workspaceEditor.markCompleted')} onPress={() => void transitionStatus('completed')} primary/><StatusAction colors={colors} disabled={saving || !mutationReady} icon="skip-next" label={t('workspaceEditor.markSkipped')} onPress={() => void transitionStatus('skipped')}/></> : <StatusAction colors={colors} disabled={saving || !mutationReady} icon="replay" label={t('workspaceEditor.markScheduled')} onPress={() => void transitionStatus('scheduled')}/>}</View></View> : null}
      {conflict ? <View accessibilityRole="alert" style={[styles.alert, {backgroundColor: colors.background.surface, borderColor: colors.state.error}]}><AppText variant="title" style={{fontSize: typography.titleSmall}}>{t('workspaceEditor.conflictTitle')}</AppText><AppText>{t('workspaceEditor.conflictBody')}</AppText></View> : null}
      {!mutationReady ? <View accessibilityRole="alert" style={[styles.alert, {backgroundColor: colors.background.surface, borderColor: colors.state.error}]}><AppText>{t('workspaceEditor.unavailable')}</AppText></View> : null}
      {errorKey === 'workspaceEditor.saveFailed' ? <View accessibilityRole="alert"><AppText style={{color: colors.state.error}}>{t(errorKey)}</AppText></View> : null}
      <Pressable accessibilityRole="button" accessibilityState={{disabled: saving || !mutationReady}} disabled={saving || !mutationReady} onPress={() => void submit()} style={[styles.save, {backgroundColor: colors.brand.primary, opacity: saving || !mutationReady ? .6 : 1}]}>{saving ? <ActivityIndicator color={colors.text.inverse}/> : <AppText style={{color: colors.text.inverse, fontWeight: typography.fontWeight.semibold}}>{t('workspaceEditor.save')}</AppText>}</Pressable>
    </ScrollView>
  </KeyboardAvoidingView>;
}
function Field({label,value,onChangeText,placeholder,error,colors}:{label:string;value:string;onChangeText:(value:string)=>void;placeholder:string;error?:string;colors:ReturnType<typeof useTheme>['colors']}) { return <View style={styles.field}><AppText style={styles.label}>{label}</AppText><TextInput accessibilityLabel={label} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={colors.text.muted} style={[styles.input,{backgroundColor:colors.background.surface,color:colors.text.primary,borderColor:error?colors.state.error:colors.border.default}]}/>{error?<View accessibilityRole="alert"><AppText style={{color:colors.state.error}}>{error}</AppText></View>:null}</View>; }
function Choice({label,selected,onPress,colors}:{label:string;selected:boolean;onPress:()=>void;colors:ReturnType<typeof useTheme>['colors']}) { return <Pressable accessibilityRole="button" accessibilityState={{selected}} onPress={onPress} style={[styles.chip,{backgroundColor:selected?colors.brand.primary:colors.background.surface,borderColor:colors.border.default}]}><AppText style={{color:selected?colors.text.inverse:colors.text.primary}}>{label}</AppText></Pressable>; }
function StatusAction({label,icon,onPress,disabled,primary=false,colors}:{label:string;icon:keyof typeof MaterialIcons.glyphMap;onPress:()=>void;disabled:boolean;primary?:boolean;colors:ReturnType<typeof useTheme>['colors']}) { return <Pressable accessibilityLabel={label} accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={[styles.statusAction,{backgroundColor:primary?colors.brand.primary:colors.background.canvas,borderColor:primary?colors.brand.primary:colors.border.default,opacity:disabled?.6:1}]}><MaterialIcons color={primary?colors.text.inverse:colors.text.primary} name={icon} size={18}/><AppText style={{color:primary?colors.text.inverse:colors.text.primary,fontWeight:typography.fontWeight.semibold}}>{label}</AppText></Pressable>; }
function SelectGroup<T extends string>({title,value,values,onChange,t,colors}:{title:string;value:T;values:readonly T[];onChange:(value:T)=>void;t:(key:string)=>string;colors:ReturnType<typeof useTheme>['colors']}) { const prefix=title.includes('Flex')||title.includes('linh hoạt')?'workspaceEditor.flexibility.':'workspaceEditor.priority.'; return <View><AppText style={styles.label}>{title}</AppText><View style={styles.chips}>{values.map((candidate)=><Choice key={candidate} label={t(`${prefix}${candidate}`)} selected={value===candidate} onPress={()=>onChange(candidate)} colors={colors}/>)}</View></View>; }
const styles=StyleSheet.create({root:{flex:1},center:{alignItems:'center',flex:1,justifyContent:'center'},content:{gap:spacing.md,padding:spacing.lg,paddingBottom:spacing.xxxl},header:{alignItems:'center',flexDirection:'row',gap:spacing.md},title:{fontSize:typography.titleSmall},iconButton:{alignItems:'center',height:44,justifyContent:'center',width:44},label:{fontSize:typography.bodySmall,fontWeight:typography.fontWeight.semibold},field:{flex:1,gap:spacing.xs},input:{borderWidth:1,borderRadius:radius.input,fontSize:typography.body,minHeight:44,paddingHorizontal:spacing.md},noteInput:{minHeight:104,paddingTop:spacing.sm},timeRow:{flexDirection:'row',gap:spacing.sm},chips:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},chip:{borderRadius:radius.pill,borderWidth:1,minHeight:44,justifyContent:'center',paddingHorizontal:spacing.md},clear:{alignSelf:'flex-start',justifyContent:'center',minHeight:44,paddingHorizontal:spacing.sm},locked:{borderRadius:radius.control,borderWidth:1,gap:spacing.xs,padding:spacing.md},lockedName:{fontWeight:typography.fontWeight.semibold},statusPanel:{borderRadius:radius.control,borderWidth:1,gap:spacing.md,padding:spacing.md},statusHeading:{alignItems:'center',flexDirection:'row',gap:spacing.sm},statusActions:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},statusAction:{alignItems:'center',borderRadius:radius.pill,borderWidth:1,flexDirection:'row',gap:spacing.xs,justifyContent:'center',minHeight:44,paddingHorizontal:spacing.md},alert:{borderRadius:radius.control,borderWidth:1,gap:spacing.sm,padding:spacing.md},save:{alignItems:'center',borderRadius:radius.pill,justifyContent:'center',minHeight:48,marginTop:spacing.md}});
