INSERT INTO places (
    name,
    city,
    category_id,
    location,
    description,
    estimated_cost,
    duration_minutes,
    indoor,
    is_active,
    is_verified,
    price_level,
    rating
)
SELECT seed.name,
       'Nha Trang',
       category.id,
       ST_GeogFromText(seed.location_wkt),
       seed.description,
       seed.estimated_cost,
       seed.duration_minutes,
       seed.indoor,
       TRUE,
       TRUE,
       seed.price_level,
       seed.rating
FROM (
    VALUES
        ('Trần Phú Beach', 'beach', 'SRID=4326;POINT(109.1968 12.2502)', 'Bãi biển trung tâm Nha Trang với dải cát dài sát đường Trần Phú.', 0.00, 120, FALSE, 'LOW', 4.6),
        ('Dốc Lết Beach', 'beach', 'SRID=4326;POINT(109.2289 12.6426)', 'Bãi biển nổi tiếng phía bắc Khánh Hòa với cát trắng và nước nông.', 50000.00, 180, FALSE, 'LOW', 4.5),
        ('Bãi Dài Beach', 'beach', 'SRID=4326;POINT(109.2008 12.0726)', 'Bãi biển dài ở khu Cam Lâm, phù hợp tắm biển và nghỉ dưỡng trong ngày.', 50000.00, 180, FALSE, 'LOW', 4.5),
        ('Sạn Beach', 'beach', 'SRID=4326;POINT(109.2145 12.3038)', 'Bãi biển phía bắc thành phố, yên tĩnh hơn khu trung tâm.', 0.00, 120, FALSE, 'LOW', 4.1),
        ('Tháp Bà Pô Nagar', 'culture', 'SRID=4326;POINT(109.195446 12.265403)', 'Quần thể tháp Chăm cổ tiêu biểu của Nha Trang, gắn với tín ngưỡng Thiên Y Thánh Mẫu.', 30000.00, 90, FALSE, 'LOW', 4.7),
        ('Viện Hải dương học Nha Trang', 'culture', 'SRID=4326;POINT(109.2144 12.2054)', 'Viện nghiên cứu biển lâu đời với khu trưng bày sinh vật biển đặc trưng.', 40000.00, 120, TRUE, 'LOW', 4.6),
        ('Chùa Long Sơn', 'spiritual', 'SRID=4326;POINT(109.180765 12.251601)', 'Ngôi chùa nổi tiếng với tượng Kim Thân Phật Tổ trắng nhìn ra toàn thành phố.', 0.00, 90, FALSE, 'LOW', 4.7),
        ('Nhà thờ Núi Nha Trang', 'spiritual', 'SRID=4326;POINT(109.1881 12.2468)', 'Nhà thờ Công giáo kiểu Gothic, còn gọi là Chánh tòa Kitô Vua.', 0.00, 60, TRUE, 'LOW', 4.6),
        ('Tháp Trầm Hương', 'check-in', 'SRID=4326;POINT(109.1967972 12.2404806)', 'Biểu tượng kiến trúc bên quảng trường 2 Tháng 4, phù hợp check-in trung tâm biển.', 0.00, 45, FALSE, 'LOW', 4.4),
        ('Vinpearl Cable Car Station', 'check-in', 'SRID=4326;POINT(109.2149 12.2087)', 'Ga cáp treo nối đất liền với Hòn Tre, điểm nhìn đẹp ra vịnh Nha Trang.', 100000.00, 60, FALSE, 'MEDIUM', 4.5),
        ('Hòn Chồng', 'check-in', 'SRID=4326;POINT(109.2019 12.2756)', 'Cụm đá ven biển nổi tiếng với truyền thuyết dấu bàn tay khổng lồ.', 30000.00, 90, FALSE, 'LOW', 4.6),
        ('Dinh Bảo Đại Nha Trang', 'check-in', 'SRID=4326;POINT(109.2148 12.2063)', 'Quần thể biệt thự trên đồi Cầu Đá gắn với giai đoạn vua Bảo Đại nghỉ dưỡng.', 50000.00, 90, FALSE, 'LOW', 4.3),
        ('VinWonders Nha Trang', 'entertainment', 'SRID=4326;POINT(109.2432 12.2278)', 'Khu vui chơi giải trí lớn trên Hòn Tre với công viên nước và show diễn.', 950000.00, 300, FALSE, 'HIGH', 4.7),
        ('I-Resort Nha Trang', 'entertainment', 'SRID=4326;POINT(109.1826 12.2747)', 'Khu tắm bùn và khoáng nóng nổi tiếng, phù hợp thư giãn nửa ngày.', 250000.00, 180, FALSE, 'MEDIUM', 4.5),
        ('Đảo Khỉ', 'entertainment', 'SRID=4326;POINT(109.2765 12.4894)', 'Đảo du lịch ở đầm Nha Phu với nhiều hoạt động ngoài trời và khỉ bán hoang dã.', 180000.00, 180, FALSE, 'MEDIUM', 4.2),
        ('Suối Hoa Lan', 'nature', 'SRID=4326;POINT(109.2550 12.4780)', 'Khu du lịch sinh thái với suối, vườn lan và không gian xanh ở đầm Nha Phu.', 180000.00, 180, FALSE, 'MEDIUM', 4.4),
        ('Đảo Hòn Mun', 'nature', 'SRID=4326;POINT(109.2990 12.1760)', 'Khu bảo tồn biển nổi tiếng cho lặn ngắm san hô ở vịnh Nha Trang.', 350000.00, 240, FALSE, 'MEDIUM', 4.7),
        ('Đảo Hòn Tằm', 'nature', 'SRID=4326;POINT(109.2469 12.1978)', 'Đảo nghỉ dưỡng gần trung tâm, nổi bật với bãi biển và các hoạt động trên biển.', 300000.00, 240, FALSE, 'MEDIUM', 4.6),
        ('Đảo Hòn Tre', 'nature', 'SRID=4326;POINT(109.2435 12.2268)', 'Hòn đảo lớn nhất vịnh Nha Trang, có nhiều bãi biển và khu nghỉ dưỡng.', 0.00, 240, FALSE, 'MEDIUM', 4.7),
        ('Thác Ba Hồ', 'nature', 'SRID=4326;POINT(109.2045 12.4310)', 'Cụm thác và hồ tự nhiên thích hợp trekking nhẹ và tắm suối.', 120000.00, 180, FALSE, 'MEDIUM', 4.5),
        ('Yang Bay Waterfall', 'nature', 'SRID=4326;POINT(108.9603 12.2905)', 'Thác nước nổi tiếng ở phía tây Nha Trang, kết hợp tham quan sinh thái.', 150000.00, 210, FALSE, 'MEDIUM', 4.4),
        ('Đầm Nha Phu', 'nature', 'SRID=4326;POINT(109.2406 12.3949)', 'Đầm nước mặn lớn phía bắc Nha Trang, cửa ngõ đi Suối Hoa Lan và Đảo Khỉ.', 0.00, 150, FALSE, 'LOW', 4.3),
        ('Chợ Đầm', 'shopping', 'SRID=4326;POINT(109.1900 12.2548)', 'Chợ trung tâm nổi tiếng với đặc sản khô, quà lưu niệm và khu ẩm thực địa phương.', 0.00, 90, TRUE, 'LOW', 4.2),
        ('Chợ đêm Nha Trang', 'shopping', 'SRID=4326;POINT(109.1950 12.2355)', 'Chợ đêm gần quảng trường biển, phù hợp dạo bộ, mua quà và ăn vặt.', 0.00, 90, FALSE, 'LOW', 4.2),
        ('Chợ Xóm Mới', 'food', 'SRID=4326;POINT(109.1898 12.2451)', 'Khu chợ địa phương nổi bật với bún chả cá, bánh căn và món ăn sáng Nha Trang.', 0.00, 75, TRUE, 'LOW', 4.4)
) AS seed(name, category_slug, location_wkt, description, estimated_cost, duration_minutes, indoor, price_level, rating)
JOIN place_categories category ON category.slug = seed.category_slug
WHERE NOT EXISTS (
    SELECT 1
    FROM places existing
    WHERE existing.name = seed.name
      AND existing.city = 'Nha Trang'
);

INSERT INTO place_tags (place_id, tag)
SELECT place.id, tag_seed.tag
FROM (
    VALUES
        ('Trần Phú Beach', 'beach'),
        ('Trần Phú Beach', 'sunrise'),
        ('Trần Phú Beach', 'city-center'),
        ('Dốc Lết Beach', 'beach'),
        ('Dốc Lết Beach', 'white-sand'),
        ('Dốc Lết Beach', 'relax'),
        ('Bãi Dài Beach', 'beach'),
        ('Bãi Dài Beach', 'coastal-drive'),
        ('Bãi Dài Beach', 'seafood'),
        ('Sạn Beach', 'beach'),
        ('Sạn Beach', 'quiet'),
        ('Sạn Beach', 'sunset'),
        ('Tháp Bà Pô Nagar', 'cham'),
        ('Tháp Bà Pô Nagar', 'heritage'),
        ('Tháp Bà Pô Nagar', 'architecture'),
        ('Viện Hải dương học Nha Trang', 'museum'),
        ('Viện Hải dương học Nha Trang', 'marine-life'),
        ('Viện Hải dương học Nha Trang', 'education'),
        ('Chùa Long Sơn', 'pagoda'),
        ('Chùa Long Sơn', 'buddha'),
        ('Chùa Long Sơn', 'viewpoint'),
        ('Nhà thờ Núi Nha Trang', 'church'),
        ('Nhà thờ Núi Nha Trang', 'gothic'),
        ('Nhà thờ Núi Nha Trang', 'landmark'),
        ('Tháp Trầm Hương', 'iconic'),
        ('Tháp Trầm Hương', 'photo-spot'),
        ('Tháp Trầm Hương', 'city-center'),
        ('Vinpearl Cable Car Station', 'cable-car'),
        ('Vinpearl Cable Car Station', 'bay-view'),
        ('Vinpearl Cable Car Station', 'photo-spot'),
        ('Hòn Chồng', 'rock-formation'),
        ('Hòn Chồng', 'coastal'),
        ('Hòn Chồng', 'photo-spot'),
        ('Dinh Bảo Đại Nha Trang', 'history'),
        ('Dinh Bảo Đại Nha Trang', 'hilltop'),
        ('Dinh Bảo Đại Nha Trang', 'museum'),
        ('VinWonders Nha Trang', 'theme-park'),
        ('VinWonders Nha Trang', 'water-park'),
        ('VinWonders Nha Trang', 'family'),
        ('I-Resort Nha Trang', 'mud-bath'),
        ('I-Resort Nha Trang', 'hot-spring'),
        ('I-Resort Nha Trang', 'relax'),
        ('Đảo Khỉ', 'family'),
        ('Đảo Khỉ', 'outdoor'),
        ('Đảo Khỉ', 'animal'),
        ('Suối Hoa Lan', 'ecotourism'),
        ('Suối Hoa Lan', 'orchid'),
        ('Suối Hoa Lan', 'outdoor'),
        ('Đảo Hòn Mun', 'snorkeling'),
        ('Đảo Hòn Mun', 'diving'),
        ('Đảo Hòn Mun', 'coral'),
        ('Đảo Hòn Tằm', 'island'),
        ('Đảo Hòn Tằm', 'beach'),
        ('Đảo Hòn Tằm', 'resort'),
        ('Đảo Hòn Tre', 'island'),
        ('Đảo Hòn Tre', 'resort'),
        ('Đảo Hòn Tre', 'bay-view'),
        ('Thác Ba Hồ', 'waterfall'),
        ('Thác Ba Hồ', 'trekking'),
        ('Thác Ba Hồ', 'nature'),
        ('Yang Bay Waterfall', 'waterfall'),
        ('Yang Bay Waterfall', 'ecotourism'),
        ('Yang Bay Waterfall', 'nature'),
        ('Đầm Nha Phu', 'lagoon'),
        ('Đầm Nha Phu', 'boat-trip'),
        ('Đầm Nha Phu', 'nature'),
        ('Chợ Đầm', 'market'),
        ('Chợ Đầm', 'local-food'),
        ('Chợ Đầm', 'souvenir'),
        ('Chợ đêm Nha Trang', 'night-market'),
        ('Chợ đêm Nha Trang', 'street-food'),
        ('Chợ đêm Nha Trang', 'shopping'),
        ('Chợ Xóm Mới', 'breakfast'),
        ('Chợ Xóm Mới', 'bun-cha-ca'),
        ('Chợ Xóm Mới', 'banh-can')
) AS tag_seed(place_name, tag)
JOIN places place
    ON place.name = tag_seed.place_name
   AND place.city = 'Nha Trang'
ON CONFLICT DO NOTHING;
